# Generated by Django 5.1 on 2024-08-23 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0012_alter_caja_fecha_hs_cier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consistencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tamaño', models.CharField(max_length=100, verbose_name='Tamaño')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='des',
            field=models.TextField(default='', verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.animal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.tamaño'),
        ),
    ]
