# Generated by Django 5.1 on 2024-08-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0013_animal_consistencia_tamaño_producto_des_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='consis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.consistencia'),
        ),
    ]
