# Generated by Django 5.1 on 2024-08-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0015_producto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
