# Generated by Django 5.1 on 2024-08-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0016_alter_producto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
