# Generated by Django 5.1 on 2024-08-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0017_alter_producto_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_r',
            field=models.IntegerField(default=0, verbose_name='Stock Reposicion'),
        ),
    ]
