# Generated by Django 5.1 on 2024-08-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0018_alter_producto_stock_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
