# Generated by Django 5.1 on 2024-08-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0019_alter_producto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenpro/'),
        ),
    ]
