# Generated by Django 5.1 on 2024-08-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0020_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
