# Generated by Django 5.1 on 2024-08-26 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MARCAS', '0021_remove_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='consis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MARCAS.consistencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
